"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.GetAllTasksController = exports.GetAllColumnsController = exports.CreateBoardController = exports.GetOneBoardController = exports.GetAllBoardController = exports.UpdateUserController = exports.GetOneUserController = exports.GetAllUserController = exports.RegisterController = exports.LoginController = void 0;
const LoginAuthController_1 = require("./Auth/LoginAuthController");
Object.defineProperty(exports, "LoginController", { enumerable: true, get: function () { return LoginAuthController_1.LoginController; } });
const RegisterAuthController_1 = require("./Auth/RegisterAuthController");
Object.defineProperty(exports, "RegisterController", { enumerable: true, get: function () { return RegisterAuthController_1.RegisterController; } });
const GetAllUserController_1 = require("./User/GetAllUserController");
Object.defineProperty(exports, "GetAllUserController", { enumerable: true, get: function () { return GetAllUserController_1.GetAllUserController; } });
const GetOneUserController_1 = require("./User/GetOneUserController");
Object.defineProperty(exports, "GetOneUserController", { enumerable: true, get: function () { return GetOneUserController_1.GetOneUserController; } });
const UpdateUserController_1 = require("./User/UpdateUserController");
Object.defineProperty(exports, "UpdateUserController", { enumerable: true, get: function () { return UpdateUserController_1.UpdateUserController; } });
const GetAllBoardController_1 = require("./Board/GetAllBoardController");
Object.defineProperty(exports, "GetAllBoardController", { enumerable: true, get: function () { return GetAllBoardController_1.GetAllBoardController; } });
const GetOneBoardController_1 = require("./Board/GetOneBoardController");
Object.defineProperty(exports, "GetOneBoardController", { enumerable: true, get: function () { return GetOneBoardController_1.GetOneBoardController; } });
const CreateBoardController_1 = require("./Board/CreateBoardController");
Object.defineProperty(exports, "CreateBoardController", { enumerable: true, get: function () { return CreateBoardController_1.CreateBoardController; } });
const GetAllColumnsController_1 = require("./Column/GetAllColumnsController");
Object.defineProperty(exports, "GetAllColumnsController", { enumerable: true, get: function () { return GetAllColumnsController_1.GetAllColumnsController; } });
const GetAllTasksController_1 = require("./Task/GetAllTasksController");
Object.defineProperty(exports, "GetAllTasksController", { enumerable: true, get: function () { return GetAllTasksController_1.GetAllTasksController; } });
