"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ISocketEvents = void 0;
var ISocketEvents;
(function (ISocketEvents) {
    ISocketEvents["boardsJoin"] = "boards:join";
    ISocketEvents["boardsLeave"] = "boards:leave";
    ISocketEvents["boardsUpdate"] = "boards:update";
    ISocketEvents["boardsUpdateSuccess"] = "boards:updateSuccess";
    ISocketEvents["boardsUpdateFailure"] = "boards:updateFailure";
    ISocketEvents["boardsDelete"] = "boards:delete";
    ISocketEvents["boardsDeleteSuccess"] = "boards:deleteSuccess";
    ISocketEvents["boardsDeleteFailure"] = "boards:deleteFailure";
    ISocketEvents["columnsDelete"] = "columns:delete";
    ISocketEvents["columnsDeleteSuccess"] = "columns:deleteSuccess";
    ISocketEvents["columnsDeleteFailure"] = "columns:deleteFailure";
    ISocketEvents["columnsCreate"] = "columns:create";
    ISocketEvents["columnsCreateSuccess"] = "columns:createSuccess";
    ISocketEvents["columnsCreateFailure"] = "columns:createFailure";
    ISocketEvents["columnsUpdate"] = "columns:update";
    ISocketEvents["columnsUpdateSuccess"] = "columns:updateSuccess";
    ISocketEvents["columnsUpdateFailure"] = "columns:updateFailure";
    ISocketEvents["tasksCreate"] = "tasks:create";
    ISocketEvents["tasksCreateSuccess"] = "tasks:createSuccess";
    ISocketEvents["tasksCreateFailure"] = "tasks:createFailure";
    ISocketEvents["tasksUpdate"] = "tasks:update";
    ISocketEvents["tasksUpdateSuccess"] = "tasks:updateSuccess";
    ISocketEvents["tasksUpdateFailure"] = "tasks:updateFailure";
    ISocketEvents["tasksDelete"] = "tasks:delete";
    ISocketEvents["tasksDeleteSuccess"] = "tasks:deleteSuccess";
    ISocketEvents["tasksDeleteFailure"] = "tasks:deleteFailure";
})(ISocketEvents = exports.ISocketEvents || (exports.ISocketEvents = {}));
