"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.routes = void 0;
const express_1 = require("express");
const middleware_1 = require("./middleware");
const controllers_1 = require("./controllers");
const controllers_2 = require("./controllers");
const routes = (0, express_1.Router)();
exports.routes = routes;
routes.post('/api/auth/login', new controllers_1.LoginController().handle);
routes.post('/api/auth/register', new controllers_1.RegisterController().handle);
routes.get('/api/users', new controllers_2.GetAllUserController().handle);
routes.get('/api/users/:id', new controllers_2.GetOneUserController().handle);
routes.put('/api/users', (0, middleware_1.ensuredAuthenticated)(), new controllers_2.UpdateUserController().handle);
routes.get('/api/user', (0, middleware_1.ensuredAuthenticated)(), (0, middleware_1.currentUser)());
routes.get('/api/boards', (0, middleware_1.ensuredAuthenticated)(), new controllers_2.GetAllBoardController().handle);
routes.post('/api/boards', (0, middleware_1.ensuredAuthenticated)(), new controllers_2.CreateBoardController().handle);
routes.get('/api/boards/:id', (0, middleware_1.ensuredAuthenticated)(), new controllers_2.GetOneBoardController().handle);
routes.get('/api/boards/:boardId/columns', (0, middleware_1.ensuredAuthenticated)(), new controllers_2.GetAllColumnsController().handle);
routes.get('/api/boards/:boardId/tasks', (0, middleware_1.ensuredAuthenticated)(), new controllers_2.GetAllTasksController().handle);
